DROP TABLE MYMEMBER;

CREATE TABLE MYMEMBER(
	MEMBERID VARCHAR2(500) PRIMARY KEY,
	MEMBERPW VARCHAR2(1000) NOT NULL,
	MEMBERNAME VARCHAR2(1000) NOT NULL
);

INSERT INTO MYMEMBER
VALUES('admin','1234','관리자');

SELECT MEMBERID, MEMBERPW, MEMBERNAME
FROM MYMEMBER;